name: Project Deployment
on:
  push:
    branches: [main]
  # workflow_dispatch:
  #   branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: npm ci
      - run: echo "ğŸ” Linting code..."
      - run: npm run lint
      - run: echo "âœ… Linting completed."
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: npm ci
      - run: echo "ğŸ” Running tests..."
      - run: npm test
      - run: echo "âœ… Tests completed."
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: npm ci
      - run: echo "ğŸ—ï¸ Building project..."
      - run: npm run build
      - run: echo "âœ… Build completed."
