name: Issues Event Details
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "ğŸ“‹ Issues..."
          echo "${{ toJSON(github.event) }}"
          echo "âœ… Event details fetched."